In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv("IMDb Movies India.csv",encoding='latin-1')

In [4]:
data.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

In [6]:
data.describe()

            Rating
count  7919.000000
mean      5.841621
std       1.381777
min       1.100000
25%       4.900000
50%       6.000000
75%       6.800000
max      10.000000

In [7]:
data.isna().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [12]:
nulls=data[data.iloc[:, 1:9].isna(). all(axis=1)]
nulls.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1836,Bang Bang Reloaded,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1920,Battle of bittora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2653,Campus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3403,Dancing Dad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3807,Dial 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
for col in data.select_dtypes(include="object"):
    print(f"Name of column: {col}")
    print(data[col].unique())
    print('\n','-'*60 ,'\n')

Name of column: Name
[' ' '#Gadhvi (He thought he was Gandhi)' '#Homecoming' ... 'Zulmi Raj'
 'Zulmi Shikari' 'Zulm-O-Sitam']

 ------------------------------------------------------------

Name of column: Year
[nan '(2019)' '(2021)' '(2010)' '(1997)' '(2005)' '(2008)' '(2012)'
 '(2014)' '(2004)' '(2016)' '(1991)' '(1990)' '(2018)' '(1987)' '(1948)'
 '(1958)' '(2017)' '(2020)' '(2009)' '(2002)' '(1993)' '(1946)' '(1994)'
 '(2007)' '(2013)' '(2003)' '(1998)' '(1979)' '(1951)' '(1956)' '(1974)'
 '(2015)' '(2006)' '(1981)' '(1985)' '(2011)' '(2001)' '(1967)' '(1988)'
 '(1995)' '(1959)' '(1996)' '(1970)' '(1976)' '(2000)' '(1999)' '(1973)'
 '(1968)' '(1943)' '(1953)' '(1986)' '(1983)' '(1989)' '(1982)' '(1977)'
 '(1957)' '(1950)' '(1992)' '(1969)' '(1975)' '(1947)' '(1972)' '(1971)'
 '(1935)' '(1978)' '(1960)' '(1944)' '(1963)' '(1940)' '(1984)' '(1934)'
 '(1955)' '(1936)' '(1980)' '(1966)' '(1949)' '(1962)' '(1964)' '(1952)'
 '(1933)' '(1942)' '(1939)' '(1954)' '(1945)' '(1961)' '(1965)' '(1938)'
 '(1941)' '(1931)' '(1937)' '(2022)' '(1932)' '(1923)' '(1915)' '(1928)'
 '(1922)' '(1917)' '(1913)' '(1930)' '(1926)' '(1914)' '(1924)']

 ------------------------------------------------------------

Name of column: Duration
[nan '109 min' '90 min' '110 min' '105 min' '147 min' '142 min' '59 min'
 '82 min' '116 min' '96 min' '120 min' '161 min' '166 min' '102 min'
 '87 min' '132 min' '66 min' '146 min' '112 min' '168 min' '158 min'
 '126 min' '94 min' '138 min' '124 min' '144 min' '157 min' '136 min'
 '107 min' '113 min' '80 min' '122 min' '149 min' '148 min' '130 min'
 '121 min' '188 min' '115 min' '103 min' '114 min' '170 min' '100 min'
 '99 min' '140 min' '128 min' '93 min' '125 min' '145 min' '75 min'
 '111 min' '134 min' '85 min' '104 min' '92 min' '137 min' '127 min'
 '150 min' '119 min' '135 min' '86 min' '76 min' '70 min' '72 min'
 '151 min' '95 min' '52 min' '89 min' '143 min' '177 min' '117 min'
 '123 min' '154 min' '88 min' '175 min' '153 min' '78 min' '139 min'
 '133 min' '101 min' '180 min' '60 min' '46 min' '164 min' '162 min'
 '171 min' '160 min' '152 min' '62 min' '163 min' '165 min' '141 min'
 '210 min' '129 min' '156 min' '240 min' '172 min' '155 min' '118 min'
 '167 min' '106 min' '193 min' '57 min' '108 min' '45 min' '195 min'
 '174 min' '81 min' '178 min' '58 min' '184 min' '97 min' '98 min'
 '131 min' '176 min' '169 min' '77 min' '91 min' '84 min' '173 min'
 '74 min' '67 min' '181 min' '300 min' '79 min' '65 min' '48 min'
 '183 min' '159 min' '83 min' '68 min' '49 min' '201 min' '64 min'
 '186 min' '50 min' '69 min' '207 min' '55 min' '61 min' '185 min'
 '187 min' '216 min' '63 min' '54 min' '198 min' '51 min' '71 min'
 '73 min' '218 min' '191 min' '321 min' '199 min' '53 min' '56 min'
 '179 min' '47 min' '206 min' '190 min' '211 min' '247 min' '213 min'
 '223 min' '2 min' '189 min' '224 min' '202 min' '255 min' '197 min'
 '182 min' '214 min' '208 min' '21 min' '200 min' '192 min' '37 min'
 '261 min' '238 min' '204 min' '235 min' '298 min' '217 min' '250 min']

 ------------------------------------------------------------

Name of column: Genre
['Drama' 'Drama, Musical' 'Comedy, Romance' 'Comedy, Drama, Musical'
 'Drama, Romance, War' 'Documentary' 'Horror, Mystery, Thriller'
 'Action, Crime, Thriller' 'Horror' 'Horror, Romance, Thriller'
 'Comedy, Drama, Romance' 'Thriller' 'Comedy, Drama' nan
 'Comedy, Drama, Fantasy' 'Comedy, Drama, Family' 'Crime, Drama, Mystery'
 'Horror, Thriller' 'Biography' 'Comedy, Horror' 'Action'
 'Drama, Horror, Mystery' 'Comedy' 'Action, Thriller' 'Drama, History'
 'Drama, History, Sport' 'Horror, Mystery, Romance' 'Horror, Mystery'
 'Drama, Horror, Romance' 'Action, Drama, History' 'Action, Drama, War'
 'Comedy, Family' 'Adventure, Horror, Mystery' 'Action, Sci-Fi'
 'Crime, Mystery, Thriller' 'War' 'Sport' 'Biography, Drama, History'
 'Horror, Romance' 'Crime, Drama' 'Drama, Romance' 'Adventure, Drama'
 'Comedy, Mystery, Thriller' 'Action, Crime, Drama' 'Crime, Thriller'
 'Horror, Sci-Fi, Thriller' 'Crime, Drama, Thriller'
 'Drama, Mystery, Thriller' 'Drama, Sport' 'Drama, Family, Musical'
 'Action, Comedy' 'Comedy, Thriller' 'Action, Adventure, Fantasy'
 'Drama, Romance, Thriller' 'Action, Drama' 'Drama, Horror, Musical'
 'Action, Biography, Drama' 'Adventure, Comedy, Drama' 'Mystery'
 'Action, Fantasy, Mystery' 'Adventure, Drama, Mystery'
 'Mystery, Thriller' 'Adventure' 'Drama, Musical, Thriller'
 'Comedy, Crime, Drama' 'Musical, Romance' 'Documentary, Music'
 'Documentary, History, Music' 'Drama, Fantasy, Mystery'
 'Drama, Family, Sport' 'Drama, Thriller' 'Documentary, Biography'
 'Action, Adventure, Comedy' 'Romance' 'Comedy, Drama, Music'
 'Comedy, Horror, Mystery' 'Musical' 'Musical, Romance, Drama'
 'Family, Romance' 'Action, Sci-Fi, Thriller' 'Action, Drama, Romance'
 'Mystery, Romance' 'Fantasy' 'Family' 'Drama, Family'
 'Action, Comedy, Drama' 'Action, Drama, Thriller'
 'Drama, Horror, Thriller' 'Drama, Musical, Romance' 'Comedy, Sci-Fi'
 'Action, Romance' 'Action, Crime' 'Action, Drama, Crime'
 'Drama, Family, Music' 'Action, Mystery, Thriller'
 'Action, Drama, Family' 'Action, Mystery' 'Drama, History, Romance'
 'Crime, Drama, Music' 'Sci-Fi' 'Animation' 'Crime, Mystery, Romance'
 'Action, Adventure, Romance' 'Music, Romance' 'Action, Comedy, Crime'
 'Comedy, Family, Fantasy' 'Romance, Drama' 'Drama, Family, Romance'
 'Romance, Drama, Family' 'Musical, Romance, Thriller'
 'Family, Musical, Romance' 'Action, Drama, Fantasy' 'Family, Drama'
 'Crime, Drama, Romance' 'Musical, Drama, Romance' 'Drama, Music, Musical'
 'Drama, Mystery' 'Adventure, Comedy, Romance' 'Crime, Drama, Horror'
 'Family, Music, Musical' 'Action, Musical, Thriller'
 'Action, Romance, Thriller' 'Romance, Thriller' 'Drama, Music'
 'Crime, Drama, Musical' 'Action, Crime, Mystery'
 'Action, Adventure, Thriller' 'Comedy, Romance, Sci-Fi' 'Crime'
 'Action, Drama, Mystery' 'Action, Comedy, Thriller' 'Biography, Drama'
 'Action, Comedy, Fantasy' 'Drama, Family, Horror'
 'Action, Adventure, Family' 'Documentary, Biography, Musical'
 'Action, Drama, Musical' 'Adventure, Thriller' 'Crime, Mystery'
 'Drama, Crime' 'Drama, Fantasy, Romance' 'Comedy, Romance, Thriller'
 'Musical, Comedy, Drama' 'Biography, History, War'
 'Action, Comedy, Romance' 'Drama, History, Musical'
 'Action, Crime, Horror' 'Adventure, Fantasy' 'Adventure, Drama, Fantasy'
 'Adventure, Fantasy, Romance' 'Action, Adventure, Drama'
 'Action, Adventure' 'Comedy, Crime' 'Crime, Drama, Fantasy'
 'Adventure, Drama, Romance' 'History' 'Drama, Fantasy, Thriller'
 'Musical, Fantasy' 'Documentary, Thriller' 'Mystery, Romance, Musical'
 'Family, Drama, Romance' 'History, Musical, Romance'
 'Musical, Drama, Crime' 'Adventure, Crime, Romance'
 'Musical, Thriller, Mystery' 'Drama, Comedy' 'Biography, Drama, Romance'
 'Biography, Music' 'Biography, Drama, Music' 'Drama, Sci-Fi'
 'Drama, Family, Thriller' 'Comedy, Musical, Romance'
 'Drama, Family, Comedy' 'Action, Thriller, Romance'
 'Animation, Adventure' 'Action, Crime, Musical' 'Action, Crime, Romance'
 'Animation, Action, Adventure' 'Action, Drama, Sport' 'Comedy, History'
 'Documentary, History' 'Drama, Comedy, Family' 'Action, Adventure, Crime'
 'Documentary, Biography, Music' 'Comedy, Musical'
 'Biography, Crime, Thriller' 'Adventure, Mystery, Thriller'
 'Biography, Drama, Sport' 'Action, Comedy, Musical'
 'Mystery, Romance, Thriller' 'Action, Adventure, Musical'
 'Crime, Musical, Mystery' 'Action, Thriller, Crime'
 'Adventure, Comedy, Crime' 'Comedy, Horror, Musical' 'Adventure, Family'
 'Family, Thriller' 'Drama, Action, Crime' 'Drama, War'
 'Action, Drama, Adventure' 'Adventure, Fantasy, History'
 'Fantasy, Musical' 'Comedy, Drama, Thriller' 'Drama, Fantasy'
 'Musical, Drama' 'Action, Drama, Horror' 'Biography, Crime, Drama'
 'Action, Drama, Music' 'Adventure, Drama, Family'
 'Drama, Romance, Musical' 'Comedy, Musical, Drama'
 'Adventure, Comedy, Musical' 'Crime, Drama, Family'
 'Thriller, Musical, Mystery' 'Documentary, Adventure, Crime'
 'Drama, Action, Horror' 'Adventure, Crime, Drama'
 'Documentary, Biography, Sport' 'Crime, Fantasy, Mystery'
 'Documentary, Biography, Drama' 'Action, Fantasy, Thriller'
 'Adventure, Drama, History' 'Animation, Drama, History'
 'Comedy, Horror, Thriller' 'Drama, Family, History' 'Animation, History'
 'Biography, Drama, Musical' 'Music' 'Family, Comedy' 'Adventure, Mystery'
 'Family, Fantasy' 'Documentary, History, News' 'Drama, Mystery, Romance'
 'Comedy, Fantasy' 'Action, Crime, Family' 'Drama, Musical, Mystery'
 'Action, Thriller, Mystery' 'Drama, Family, Fantasy' 'Action, Family'
 'Action, Adventure, Mystery' 'Horror, Fantasy' 'Comedy, Action'
 'Adventure, Romance' 'Drama, Adventure' 'Animation, Drama, Romance'
 'Comedy, Crime, Romance' 'Adventure, Comedy' 'Comedy, Drama, Sport'
 'Documentary, Crime, History' 'Musical, Mystery, Drama'
 'Adventure, Drama, Sci-Fi' 'Action, Romance, Western'
 'Comedy, Fantasy, Romance' 'Animation, Action, Comedy'
 'Drama, Fantasy, Sci-Fi' 'Drama, Horror' 'Family, Drama, Comedy'
 'Action, Adventure, History' 'Comedy, Family, Romance'
 'Biography, History' 'Animation, Family' 'Drama, Fantasy, History'
 'Animation, Adventure, Fantasy' 'Adventure, Comedy, Family'
 'Drama, History, War' 'Animation, Drama, Fantasy'
 'Action, Musical, Romance' 'Crime, Action, Drama'
 'Comedy, Romance, Musical' 'Fantasy, Drama' 'Musical, Action, Crime'
 'Documentary, Drama' 'Action, Horror, Thriller' 'Action, Horror, Sci-Fi'
 'Mystery, Sci-Fi, Thriller' 'Biography, Family' 'Drama, Action, Comedy'
 'Drama, Music, Romance' 'Action, Biography, Crime'
 'Adventure, Drama, Musical' 'Family, Music, Romance'
 'Fantasy, Mystery, Romance' 'Drama, Crime, Family'
 'Drama, Family, Action' 'Romance, Comedy, Drama'
 'Animation, Adventure, Comedy' 'Sci-Fi, Thriller'
 'Romance, Family, Drama' 'Action, Family, Thriller'
 'Adventure, Crime, Thriller' 'Drama, Romance, Sport'
 'Comedy, Crime, Mystery' 'Adventure, Comedy, Mystery' 'Action, Fantasy'
 'Comedy, Mystery' 'Animation, Adventure, Family'
 'Adventure, Drama, Music' 'Biography, Drama, War'
 'Documentary, Comedy, Drama' 'Musical, Drama, Family'
 'Animation, Comedy, Drama' 'Fantasy, Musical, Drama'
 'Adventure, Crime, Mystery' 'Comedy, Drama, Mystery' 'Documentary, News'
 'Drama, Musical, Family' 'Action, Romance, Drama'
 'Comedy, Crime, Thriller' 'Action, Musical' 'Action, History'
 'Action, Comedy, Mystery' 'Drama, Family, Mystery'
 'Adventure, Drama, Thriller' 'Documentary, Reality-TV'
 'Action, Fantasy, Horror' 'Drama, History, Thriller'
 'Documentary, Family' 'Documentary, Biography, Family' 'Comedy, Sport'
 'Animation, Comedy, Family' 'Crime, Romance, Thriller'
 'Comedy, Musical, Action' 'Action, Mystery, Sci-Fi'
 'Comedy, Crime, Musical' 'Drama, Adventure, Action' 'History, Romance'
 'Reality-TV' 'Fantasy, History' 'Family, Drama, Thriller'
 'Musical, Mystery, Thriller' 'Musical, Comedy, Romance'
 'Musical, Action, Drama' 'Action, Musical, War' 'Romance, Comedy'
 'Horror, Crime, Thriller' 'Crime, Drama, History' 'Comedy, Drama, Horror'
 'Crime, Horror, Thriller' 'Animation, Comedy' 'Romance, Action, Crime'
 'Musical, Thriller' 'Action, Romance, Comedy' 'Comedy, Family, Musical'
 'Horror, Drama, Mystery' 'Thriller, Mystery, Family'
 'Comedy, Drama, Sci-Fi' 'Documentary, Adventure'
 'Documentary, Biography, Crime' 'Musical, Action' 'Musical, Mystery'
 'Action, Crime, Sci-Fi' 'Action, Horror, Mystery' 'Fantasy, Horror'
 'Adventure, Family, Fantasy' 'Fantasy, Sci-Fi' 'Comedy, War'
 'Romance, Action, Drama' 'Musical, Family, Romance'
 'Romance, Drama, Action' 'Family, Comedy, Drama' 'Comedy, Music, Romance'
 'Comedy, Family, Sci-Fi' 'Action, Drama, Western'
 'Adventure, Romance, Thriller' 'Biography, Comedy, Drama'
 'Action, Mystery, Romance' 'Romance, Sport' 'Crime, Romance'
 'Action, Thriller, Western' 'Crime, Musical, Romance'
 'Romance, Thriller, Mystery' 'Drama, Crime, Mystery'
 'Biography, Drama, Family' 'Action, Family, Mystery'
 'Comedy, Mystery, Romance' 'Drama, Thriller, Action' 'Documentary, Short'
 'Documentary, Western' 'Musical, Family, Drama' 'Action, Family, Musical'
 'Animation, Family, Musical' 'Drama, Fantasy, Horror'
 'Action, Adventure, Sci-Fi' 'Drama, Action, Musical'
 'Drama, Musical, Sport' 'Action, Comedy, Horror'
 'Drama, Fantasy, Musical' 'Action, Fantasy, Musical' 'Animation, Action'
 'Comedy, Music' 'Documentary, Drama, Romance' 'Drama, Music, Thriller'
 'Fantasy, Musical, Mystery' 'Drama, Fantasy, War' 'Action, War'
 'Action, Adventure, War' 'Horror, Musical' 'Fantasy, Mystery, Thriller'
 'Adventure, Biography, Drama' 'Family, Romance, Sci-Fi'
 'Drama, Romance, Family' 'Animation, Adventure, Drama'
 'Family, Romance, Drama' 'Animation, Action, Sci-Fi'
 'Adventure, Comedy, Fantasy' 'Comedy, Crime, Family'
 'Horror, Musical, Thriller' 'Biography, Drama, Thriller' 'Drama, Western'
 'Romance, Sci-Fi, Thriller' 'Comedy, Musical, Family'
 'Comedy, Horror, Romance' 'Thriller, Action' 'Fantasy, Thriller, Action'
 'Fantasy, Romance' 'Action, Drama, Comedy' 'Family, Fantasy, Romance'
 'Comedy, Crime, Horror' 'Horror, Mystery, Sci-Fi'
 'Animation, Action, Drama' 'Family, Mystery'
 'Adventure, Biography, History' 'Fantasy, Horror, Mystery'
 'Family, Musical' 'Drama, Family, Adventure' 'Crime, Horror, Mystery'
 'Documentary, Drama, Fantasy' 'Action, Adventure, Biography'
 'Biography, History, Thriller' 'Action, Family, Drama'
 'Documentary, Drama, Sport' 'Thriller, Mystery' 'Musical, Drama, Comedy'
 'Documentary, History, War' 'Adventure, Horror, Thriller'
 'Action, Adventure, Horror' 'Action, Crime, War'
 'Adventure, Musical, Romance' 'Action, Fantasy, Sci-Fi'
 'Drama, Comedy, Action' 'Documentary, Sport'
 'Documentary, Adventure, Music' 'Drama, Action, Family'
 'Adventure, History, Thriller' 'Adventure, Horror, Romance'
 'Adventure, Crime, Horror' 'Mystery, Musical, Romance'
 'Action, Crime, History' 'Documentary, Musical'
 'Adventure, Fantasy, Musical' 'Documentary, Family, History'
 'Documentary, Drama, Family' 'Drama, Mystery, Sci-Fi'
 'Animation, Drama, Musical' 'Drama, History, Mystery'
 'Drama, Sport, Thriller' 'Action, Crime, Fantasy'
 'Comedy, Musical, Mystery' 'Romance, Musical, Action'
 'Musical, Drama, Fantasy' 'Animation, Family, History'
 'Action, Drama, News' 'Romance, Musical, Comedy'
 'Adventure, Fantasy, Horror' 'Adventure, History'
 'Comedy, Drama, History' 'Mystery, Sci-Fi' 'Action, Thriller, War'
 'Documentary, Drama, News' 'Documentary, Crime, Mystery'
 'Adventure, Horror' 'Animation, Drama, Adventure'
 'Crime, Horror, Romance' 'Documentary, Adventure, Drama'
 'Documentary, Biography, History' 'Fantasy, Horror, Romance'
 'Comedy, Fantasy, Musical' 'Crime, Musical, Thriller' 'Documentary, War'
 'Action, Comedy, War' 'Crime, Drama, Sport' 'Musical, Adventure, Drama'
 'Horror, Romance, Sci-Fi' 'Musical, Mystery, Romance'
 'Romance, Musical, Drama' 'Adventure, Fantasy, Sci-Fi']

 ------------------------------------------------------------

Name of column: Votes
[nan '8' '35' ... '70,344' '408' '1,496']

 ------------------------------------------------------------

Name of column: Director
['J.S. Randhawa' 'Gaurav Bakshi' 'Soumyajit Majumdar' ... 'Mozez Singh'
 'Ved Prakash' 'Kiran Thej']

 ------------------------------------------------------------

Name of column: Actor 1
['Manmauji' 'Rasika Dugal' 'Sayani Gupta' ... 'Meghan Jadhav'
 'Roohi Berde' 'Sangeeta Tiwari']

 ------------------------------------------------------------

Name of column: Actor 2
['Birbal' 'Vivek Ghamande' 'Plabita Borthakur' ... 'Devan Sanjeev'
 'Prince Daniel' 'Sarah Jane Dias']

 ------------------------------------------------------------

Name of column: Actor 3
['Rajendra Bhatia' 'Arvind Jangid' 'Roy Angana' ... 'Shatakshi Gupta'
 'Valerie Agha' 'Suparna Anand']

 ------------------------------------------------------------